import '@/styles/globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import { Inter } from 'next/font/google'

import { ThemeProvider } from '@mui/material/styles'

import theme from '@/lib/theme'
import { TRPCReactProvider } from '@/trpc/react'

const inter = Inter({
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
